### ISSUE TITLE
Sometimes trade events are not triggered

### ISSUE THREAD

**Issue by lnfecteDru** [Gobot1234/steam.py#100]
### Summary

Trade events are not triggered sometimes

### Reproduction Steps

```
import json
import steam

bot = steam.Client(state=steam.PersonaState.Invisible)

@bot.event
async def on_ready():
    print('Client is ready!')

@bot.event
async def on_trade_receive(trade: steam.TradeOffer):
    print('New trade offer received')

@bot.event
async def on_trade_accept(trade: steam.TradeOffer):
    print('Trade offer accepted')

@bot.event
async def on_trade_decline(trade: steam.TradeOffer):
    print('Trade offer declined')

with open('credentials.json') as f:
    credentials = json.load(f)

bot.run(**credentials)
```
_File "credentials.json" contains valid username, password, secret and shared keys_

### Expected Results

_New trade offer received_
or
_Trade offer accepted_
or
_Trade offer declined_

### Actual Results

Nothing

### System Information

python version: 3.8.12
steam.py version: 0.8.6
aiohttp version: 3.8.1
betterproto version: 2.0.0b4
operating system info: Windows-10-10.0.19044-SP0

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username/password/secrets from display, if visible.

**Comment by Gobot1234** [comment]
This might be because you set your state to Offline although I haven't tested this theory

**Comment by lnfecteDru** [comment]
Just checked, the same thing happens with Online state too

**Comment by Gobot1234** [comment]
I can't reproduce this do you have logs set up for the bot? If you do please could you email me (gobot1234yt@gmail.com) or DM me on Discord (Gobot1234#2435) with them?

**Comment by Gobot1234** [comment]
AFAICT this should now be fixed if you install 0.8.7, please re-open if not

**Comment by lnfecteDru** [comment]
For some reason it started happening again. In log I found this error:
_2022-04-09 16:52:08,144:INFO:steam.state: Error while polling trades
Traceback (most recent call last):
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc_updated\lib\site-packages\steam\state.py", line 329, in fill_trades
    trades = await self.http.get_trade_offers()
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc_updated\lib\site-packages\steam\http.py", line 437, in get_trade_offers
    value_in_first_page = first_page[key]
KeyError: 'descriptions'_

I can provide full log if needed

**Comment by lnfecteDru** [comment]
The error has disappeared but trade events are still not triggered

System information:
python version: 3.8.13
steam.py version: 0.9.0a2176+gec10e5c
aiohttp version: 3.8.1
betterproto version: 2.0.0b4
operating system info: Windows-10-10.0.19044-SP0

**Comment by Gobot1234** [comment]
> The error has disappeared but trade events are still not triggered
> 
> 
> 
> System information:
> 
> python version: 3.8.13
> 
> steam.py version: 0.9.0a2176+gec10e5c
> 
> aiohttp version: 3.8.1
> 
> betterproto version: 2.0.0b4
> 
> operating system info: Windows-10-10.0.19044-SP0

I'm gonna need the logs then

**Comment by lnfecteDru** [comment]
Suddenly it happened again. There are constant GetTradeOffers requests every ~0.5sec in logs.

System information:
python version: 3.8.13
steam.py version: 0.9.0a2206+g58e06e8
aiohttp version: 3.8.1
betterproto version: 2.0.0b4
operating system info: Windows-10-10.0.19044-SP0

**Comment by lnfecteDru** [comment]
Recently it started to skip too much trades and sometimes client cannot accept trade (it just stucks during trade.accept()). In logs I discovered some new trade related errors (I listed only the different ones), I hope it will help.
```
2022-07-16 17:29:53,464:INFO:steam.state: Error while polling trades
Traceback (most recent call last):
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 311, in _store_trade
    trade = self._trades[int(data["tradeofferid"])]
KeyError: 5325919581

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 371, in fill_trades
    received_trades = await self._process_trades(updated_received_trades, descriptions)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 346, in _process_trades
    ret.append(await self._store_trade(trade))
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 314, in _store_trade
    trade = TradeOffer._from_api(
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 573, in _from_api
    trade._update(data)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 621, in _update
    self.items_to_receive = [
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 622, in <listcomp>
    Item(self._state, data=item, owner=self.partner) for item in data.get("items_to_receive", [])
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 197, in __init__
    self._from_data(data)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 210, in _from_data
    else f"https://steamcommunity-a.akamaihd.net/economy/image/{data['icon_url']}"
KeyError: 'icon_url'
```
```
2022-07-16 17:42:05,092:INFO:steam.state: Error while polling trades
Traceback (most recent call last):
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 371, in fill_trades
    received_trades = await self._process_trades(updated_received_trades, descriptions)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 346, in _process_trades
    ret.append(await self._store_trade(trade))
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 325, in _store_trade
    trade._update(data)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 621, in _update
    self.items_to_receive = [
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 622, in <listcomp>
    Item(self._state, data=item, owner=self.partner) for item in data.get("items_to_receive", [])
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 197, in __init__
    self._from_data(data)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 210, in _from_data
    else f"https://steamcommunity-a.akamaihd.net/economy/image/{data['icon_url']}"
KeyError: 'icon_url'
```
```
2022-07-16 17:30:29,177:INFO:steam.state: Error while polling trades
Traceback (most recent call last):
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 371, in fill_trades
    received_trades = await self._process_trades(updated_received_trades, descriptions)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 346, in _process_trades
    ret.append(await self._store_trade(trade))
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 325, in _store_trade
    trade._update(data)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 618, in _update
    self.items_to_send = [
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 619, in <listcomp>
    Item(self._state, data=item, owner=self.partner) for item in data.get("items_to_give", [])
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 197, in __init__
    self._from_data(data)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/trade.py", line 210, in _from_data
    else f"https://steamcommunity-a.akamaihd.net/economy/image/{data['icon_url']}"
KeyError: 'icon_url'
```
```
2022-07-16 17:51:40,136:INFO:steam.state: Error while polling trades
Traceback (most recent call last):
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 365, in fill_trades
    trades = await self.http.get_trade_offers()
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/http.py", line 432, in get_trade_offers
    resp = await self.get(api_route("IEconService/GetTradeOffers"), params=params)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/http.py", line 98, in request
    async with self._session.request(method, url, **kwargs, proxy=self.proxy, proxy_auth=self.proxy_auth) as r:
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Comment by Gobot1234** [comment]
Thanks for letting me know, I've fixed the KeyErrors, I'm not entirely sure what I could do about the last one it looks like it's just timing out wating for the request.

**Comment by lnfecteDru** [comment]
There's new trade-related error started to appear:
```
2022-07-22 09:21:21,214:INFO:steam.state: Error while polling trades
Traceback (most recent call last):
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/state.py", line 365, in fill_trades
    trades = await self.http.get_trade_offers()
  File "/home/lnfectedru/miniconda3/envs/tfgc/lib/python3.8/site-packages/steam/http.py", line 446, in get_trade_offers
    next_cursor = page["next_cursor"]
KeyError: 'next_cursor'
```

**Comment by lnfecteDru** [comment]
Looks like there's an infinite loop in 'get_trade_offers' which prevents trades from being received:
```
...
next_cursor = first_page.get("next_cursor", 0)
current_cursor = 0
while current_cursor != next_cursor:
    params["cursor"] = next_cursor
    resp = await self.get(api_route("IEconService/GetTradeOffers"), params=params)
    page = resp["response"]
    for key, value in page.items():
        value_in_first_page = first_page[key]
        if isinstance(value_in_first_page, list):
            value_in_first_page += value

    current_cursor = next_cursor
    try:
        next_cursor = page["next_cursor"]
    except KeyError:
        break
...
```

After the last page, 'next_cursor' is still received and equals 0, so the loop condition 'current_cursor != next_cursor' never fails and, in fact, starts getting trade history again, and this only can be stopped by random KeyError. The possible solution is to check for 'current_cursor < next_cursor' instead, or 'next_cursor > 0'. Both solutions worked for me and partially fixed the issue (at least during the testing time).

**Comment by Gobot1234** [comment]
Thanks, I've gone with the first solution you gave.

**Comment by lnfecteDru** [comment]
I believe, there's a possibility of some trades being ignored (function `get_trade_offers`):
```
if updated_only:
    try:
        params["time_historical_cutoff"] = self.trades_last_fetched
    except AttributeError:
        pass
    self.trades_last_fetched = int(time()) # <- here
...
```

In case of `TimeoutError` during `GetTradeOffers` api call inside of the loop below, the value of `trades_last_fetched` will still be updated like as if all the trades would be successfully processed. It can be moved after the loop (so it won't be updated in case of error) or, as a better but a bit more complex solution, it can be equal to max `time_created` value of successfully processed trades.

**Comment by lnfecteDru** [comment]
I deleted my last message due to my incorrect interpretation of purpose of the parameter `time_historical_cutoff`, but I noticed that it's still relevant for trade state update issue. So, the thing is, in function `get_trade_offers` parameter `trades_last_fetched` is updated whether api call `GetTradeOffers` successful or not, which can cause issues with updating of trades states. A possible solution is to set the parameter after the loop:
```
if updated_only:
    try:
        params["time_historical_cutoff"] = self.trades_last_fetched
    except AttributeError:
        pass

resp = await self.get(api_route("IEconService/GetTradeOffers"), params=params)
first_page = resp["response"]
next_cursor = first_page.get("next_cursor", 0)
current_cursor = 0
while current_cursor < next_cursor:
    params["cursor"] = next_cursor
    resp = await self.get(api_route("IEconService/GetTradeOffers"), params=params)
    page = resp["response"]
    for key, value in page.items():
        value_in_first_page = first_page[key]
        if isinstance(value_in_first_page, list):
            value_in_first_page += value

    current_cursor = next_cursor
    try:
        next_cursor = page["next_cursor"]
    except KeyError:
        break

if updated_only:
    self.trades_last_fetched =  = int(time())

return first_page
```
Or, a better solution would be setting the value to max of `time_updated` of successfully processed trades, something like this:
```
def _update_trades_last_fetched(self, page):
    if 'trade_offers_received' not in page:
        return
    
    received_trades = page['trade_offers_received']
    max_last_fetched = max(rt['time_updated'] for rt in received_trades if 'time_updated' in rt)
    
    try:
        self.trades_last_fetched = max(max_last_fetched, self.trades_last_fetched)
    except AttributeError:
        self.trades_last_fetched = max_last_fetched
```
```
async def get_trade_offers(...) -> dict[str, Any]:
    params = {
        "key": self.api_key,
        "active_only": str(active_only).lower(),
        "get_sent_offers": str(sent).lower(),
        "get_received_offers": str(received).lower(),
        "get_descriptions": "true",
        "cursor": 0,
    }
    if updated_only:
        try:
            params["time_historical_cutoff"] = self.trades_last_fetched
        except AttributeError:
            pass
    
    resp = await self.get(api_route("IEconService/GetTradeOffers"), params=params)
    first_page = resp["response"]
    self._update_trades_last_fetched(first_page)
    
    next_cursor = first_page.get("next_cursor", 0)
    current_cursor = 0
    while current_cursor < next_cursor:
        params["cursor"] = next_cursor
        resp = await self.get(api_route("IEconService/GetTradeOffers"), params=params)
        page = resp["response"]
        self._update_trades_last_fetched(page)
        for key, value in page.items():
            value_in_first_page = first_page[key]
            if isinstance(value_in_first_page, list):
                value_in_first_page += value

        current_cursor = next_cursor
        try:
            next_cursor = page["next_cursor"]
        except KeyError:
            break
    
    return first_page
```

**Comment by Gobot1234** [comment]
I don't see how the second is better, it seems more complicated and more error prone

**Comment by lnfecteDru** [comment]
> I don't see how the second is better, it seems more complicated and more error prone can you explain why it's better than the first?

I agree that the second one is more error-prone. But it is more precise, which eliminates possibility of some trade being ignored if received during the time between last `GetTradeOffers` (+latency) and setting the value of `trades_last_fetched`

**Comment by Gobot1234** [comment]
I don't see that ever being an issue, so I'm just going to use the first solution
